// Generated by CoffeeScript 1.8.0
(function() {
  var app;

  app = angular.module('TFTM', ["ngRoute"]);

  app.config([
    '$routeProvider', '$locationProvider', function($routeProvider, $locationProvider) {
      $routeProvider.when('/', {
        templateUrl: '../templates/home.html',
        controller: 'HomePageController'
      });
      $routeProvider.when('/battleship', {
        templateUrl: '../templates/battleship/home.html',
        controller: 'BattleshipController'
      });
      $routeProvider.when('/about', {
        templateUrl: '../templates/about.html'
      });
      return $locationProvider.html5Mode(true);
    }
  ]);

  app.directive('navBar', function() {
    return {
      restrict: 'E',
      templateUrl: '../templates/navbar/nav.html',
      controller: 'NavBarController',
      controllerAs: 'navBar'
    };
  });

  app.directive('contentFooter', function() {
    return {
      restrict: 'E',
      templateUrl: '../templates/footer.html'
    };
  });

  app.directive('pageList', function() {
    return {
      restrict: 'A',
      templateUrl: '../templates/navbar/page-list.html'
    };
  });

  app.controller('HomePageController', function($rootScope) {
    return $rootScope.doc_title = 'TFTM | Online multiplayer browser games';
  });

  app.controller('NavBarController', function($scope, $location) {
    $scope.pages = [
      {
        url: '/',
        name: 'Главная'
      }, {
        name: 'Игры',
        pages: [
          {
            url: '/battleship',
            name: 'Морской бой'
          }
        ]
      }
    ];
    $scope.rightPages = [
      {
        url: '/about',
        name: 'О проекте'
      }
    ];
    return $scope.current = function() {
      return $location.path();
    };
  });

  app.controller('BattleshipController', function($scope) {
    return $scope.pages = [
      {
        url: '/battleship',
        name: 'Battleship'
      }
    ];
  });

}).call(this);
